### ISSUE TITLE
* Either moxi_works_agent_id or agent_uuid must be supplied. For guidance on which Agent identifier better fits your use-case, see Agent Identifiers

### ISSUE THREAD

**Issue by Th3An1m4l** [moxiworks-platform/moxiworks-php#2]
In the library code I've found error in Agent.php like

` public static function find($attributes=[]) {
        $url = Config::getUrl() . "/api/agents/" . $attributes['moxi_works_agent_id'];
        return Agent::sendRequest('GET', $attributes, $url);
    }
`
that makes "moxi_works_agent_id" required in attributes

the same here 

`
    public static function search($attributes=[]) {
        $method = 'GET';
        $url = Config::getUrl() . "/api/agents";
        $agents = array();

        $required_opts = array('moxi_works_agent_id','moxi_works_company_id');

        if(count(array_intersect(array_keys($attributes), $required_opts)) != count($required_opts))
            throw new ArgumentException(implode(',', $required_opts) . " are required");

        $json = Resource::apiConnection($method, $url, $attributes);

        if(!isset($json) || empty($json))
            return null;

        foreach ($json['agents'] as $c) {
            $agent = new Agent($c);
            array_push($agents, $agent);
        }
        $json['agents'] = $agents;
        return $json;
    }
`
"moxi_works_agent_id" is required

but in API told that it might be used as OR presence

that's why I should use

`
$agent = MoxiworksPlatform\Agent::find([
                        'agent_uuid' => $listing->list_agent_uuid,
                        'moxi_works_agent_id' => $listing->list_agent_uuid,
                        'moxi_works_company_id' => $moxi_works_company_id]);
`

instead of 

`$agent = MoxiworksPlatform\Agent::find([
                        'agent_uuid' => $listing->list_agent_uuid,
                        'moxi_works_company_id' => $moxi_works_company_id]);
`

Is that bug or I'm doing something wrong?

**Comment by tres** [comment]
@Th3An1m4l  Thanks for your report!

I do apologize for the delay in getting back to you about this.

I've updated the library and published 0.12.1 to packagist.

Please try out the updated version.

Let me know if there are any additional issues.

Again, my apologies for the delay in response. 

Regards,
Tres
