### ISSUE TITLE
PHP error on Either moxi_works_agent_id or agent_uuid must be supplied

### ISSUE THREAD

**Issue by rahmn** [moxiworks-platform/moxiworks-php#3]
Kylah confirmed with Engineering that this is a bug and asked us to sumbit here:

from our developer:

---

I have question regarding API

in the latest changes list they wrote

API |Allow 'uuid' To Be Passed Where We Currently Accept 'moxi_works_agent_id'

in the latest API they wrote

Send a GET request to https://api.moxiworks.com/api/agents/[agent identifier]

* Either moxi_works_agent_id or agent_uuid must be supplied. For guidance on which Agent identifier better fits your use-case, see Agent Identifiers

In the listing Object we have only

ListAgentUUID and  SecondaryListAgentUUID

when I'm trying fetch agent with code from example

    $moxi_works_agent = MoxiworksPlatform\Agent::find([
                        'agent_uuid' => $listing->list_agent_uuid,
                        'moxi_works_company_id' => $moxi_works_company_id]);

it causes error because in the PHP client library I've found next code

    public static function find($attributes=[]) {
        $url = Config::getUrl() . "/api/agents/" . $attributes['moxi_works_agent_id'];
        return Agent::sendRequest('GET', $attributes, $url);
    }
 

    private static function sendRequest($method, $opts=[], $url=null) {
        if($url == null) {
            $url = Config::getUrl() . "/api/agents";
        }
        $required_opts = array('moxi_works_agent_id', 'moxi_works_company_id');
        if(count(array_intersect(array_keys($opts), $required_opts)) != count($required_opts))
            throw new ArgumentException(implode(',', $required_opts) . " required");
        $agent = null;
        $json = Resource::apiConnection($method, $url, $opts);
        $agent = (!isset($json) || empty($json)) ? null : new Agent($json);
        return $agent;
    }

where 

    $required_opts = array('moxi_works_agent_id', 'moxi_works_company_id');

tells us that is required field in spite of the fact that in API the tell

* Either moxi_works_agent_id or agent_uuid must be supplied. For guidance on which Agent identifier better fits your use-case, see Agent Identifiers

but now I try to fetch agent with next string call

    $agent = MoxiworksPlatform\Agent::find([
                        'agent_uuid' => $listing->list_agent_uuid,
                        'moxi_works_agent_id' => $listing->list_agent_uuid,
                        'moxi_works_company_id' => $moxi_works_company_id]);
 
where I pass list_agent_uuid twice and it woks in that way.

so back to 

API |Allow 'uuid' To Be Passed Where We Currently Accept 'moxi_works_agent_id' 

I have  a question

does my call is right or they should update PHP client library?

**Comment by tres** [comment]
Hi @rahmn 

Thanks for your report.

I've looked at this and determined that the library was not reflecting the documentation / raw endpoint parameters available.

I'll update the library and push a new version that should be picked up by Packagist.

I'll update this ticket once the new version has been picked up & is available.

Thanks again,
Tres

**Comment by tres** [comment]
Hi @rahmn version 0.12.1 should be available via packagist. 

Thanks again for your report.
