### ISSUE TITLE
Documentation is different then support for agent_uuid arguments in the Contact class.

### ISSUE THREAD

**Issue by jclaybrook** [moxiworks-platform/moxiworks-php#6]
Based on the documentation found at the URL below the Contact Create endpoint in the PHP class should support using either the "agent_uuid" or the "moxi_works_agent_id". 

http://moxiworks-platform.github.io/?php#contact-create

However in the Contact class when Contact::create() calls the sendRequest() method the "moxi_works_agent_id" argument is required, so if you try and use the "agent_uuid" argument instead, it fails on the following lines of code with a missing argument exception.

From Contact.php sendRequest()
`$required_opts = array('partner_contact_id', 'moxi_works_agent_id');
 if(count(array_intersect(array_keys($opts), $required_opts)) != count($required_opts))
            throw new ArgumentException(implode(',', $required_opts) . " are required");`

**Comment by tres** [comment]
Thanks for letting us know about the issue. 

We'll be taking a look at it and getting back to you as soon as we can.

**Comment by tres** [comment]
Hi,

Thanks again for letting us know about this issue. We've pushed 0.13.13 to Packagist, which should resolve this issue.

**Comment by jclaybrook** [comment]
Thanks Tres

**Comment by tres** [comment]
Hey Jason,

Looks like there was a syntax issue with the implementation in 0.13.13. I've pushed 0.13.14 to fix that. 

Thanks again for the report & sorry for the extra cycle here.

Tres
