### ISSUE TITLE
in the Office.php the property client_office_id is missing

### ISSUE THREAD

**Issue by arvindsolanki9725** [moxiworks-platform/moxiworks-php#7]
Please add the client_office_id field as per the documentation which is missing in the class file property due to which i am not able to get the required details.

**Comment by kotauttejreddy** [comment]
added the necessary code in the following commit
https://github.com/moxiworks-platform/moxiworks-php/pull/8/commits/1b792c54c2456220c06396371af38333ae0cb1ef

**Comment by tres** [comment]
Thanks, @kotauttejreddy!

thanks for your report @arvindsolanki9725 you should be able to get 0.13.16 from packagist as soon as the change is picked up
